---
title: "Laboratorio didattico"
subtitle: "The Psychological Burden of the COVID-19"
author: "None"
date: "`r format(Sys.Date())`"
output:
  html_document:
    highlight: pygments
    fig_caption: yes
    toc: TRUE
    toc_depth: 2
    number_sections: TRUE
    toc_float:
      smooth_scroll: FALSE
---

Carico i pacchetti necessari:
```{r}
suppressPackageStartupMessages({
  library("tidyverse")
  library("here")
  library("rio")
  library("brms")
  library("psych")
  library("cmdstanr")
})
```

Lettura dei dati:
```{r}
df <- rio::import(here::here("DatiR", "hope_violence_final.dta"))
```

Per capire a cosa corrisponda la codifica di `country` conto il numero di casi in ciascun paese e in ciascuna wave. 
```{r}
table(df$wave, df$country)
```
glimpse()   #ho corretto :)
```{r}
gender_items <- df %>%
  select("gender")
gender <- rowSums(gender_items) 
hist(gender)
```

```{r}
country_items <- df %>%
  select("country")
country <- rowSums(country_items) 
hist(country)
```
#GiuliaViliani: selezione dal data.frame della sezione "race" + sua rappresetazione in un istogramma e creazione del vettore race_items
```{r}
race_items <- df %>%
  select("race")
race <- rowSums(race_items)
hist(race)
```

#VirginiaSimoncini:
```{r}
education_items <- df %>%
  select("education_rc")
education <- rowSums(education_items)
hist(education)
```

